services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - apigateway

  apigateway:
    container_name: apigateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    depends_on:
      - customerservice
      - productservice
      - orderservice
      - paymentservice

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    expose:
      - "15672"
      - "5672"

  customerservice:
    container_name: customerservice
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/db/customer.db"
    volumes:
      - ./CustomerService/db:/app/db

  productservice:
    container_name: productservice
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/db/product.db"
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /
      RabbitMq__ExchangeName: orders.exchange
      RabbitMq__OrderCreatedQueueName: product.order-created.queue
    volumes:
      - ./ProductService/db:/app/db
    depends_on:
      - rabbitmq

  orderservice:
    container_name: orderservice
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/db/order.db"
      ServiceUrls__CustomerService: http://customerservice:8080/
      ServiceUrls__ProductService: http://productservice:8080/
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /
      RabbitMq__ExchangeName: orders.exchange
    volumes:
      - ./OrderService/db:/app/db
    depends_on:
      - rabbitmq
      - customerservice
      - productservice

  paymentservice:
    container_name: paymentservice
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/db/payment.db"
    volumes:
      - ./PaymentService/db:/app/db